name: 02-workflow-events

on: 
 
  pull_request:
  workflow_dispatch:
  push:  
      

jobs: 
    echo:
        runs-on: ubuntu-latest
        steps: 
            - name: Show the trigger
              run: echo "I have been triggered by a(n) ${{github.event_name}} event"

