name: 04-using-actions-updated


on: workflow_dispatch

jobs: 
    build:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node 
              uses: actions/setup-node@v4
              with: 
                node-version: '20.x'
            - name: Install dependencies
              run: npm ci  
              working-directory: 04-using-actions/react-app    
              #run: |
                #cd 04-using-actions/react-app
                #npm ci





        # 1. install react app
        # 2. execute automated tests

